[phases.setup]
nixPkgs = ["nodejs-18_x", "npm-9_x"]

[phases.install]
cmds = [
  "npm install --no-package-lock"
]

[phases.build]
cmds = [
  "npm run build:railway"
]

[start]
cmd = "npm start"

[build]
cache_directories = []
